version: '3.1'

services:
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migrations
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PWD=${DB_PWD:-postgres}
      - DB_NAME=${DB_PWD:-oms}
    networks:
      - mynet
    depends_on:
      - db

  coinbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coinbase
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PWD=${DB_PWD:-postgres}
      - DB_NAME=${DB_PWD:-oms}
    networks:
      - mynet
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PWD:-password}
    networks:
      - mynet
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  mynet:
    driver: bridge

volumes:
  mysql-data:

